### PR TITLE
redux-subspace version 2 - Spliting packages, better middleware support, redux-saga support, improved docs

### PR DESCRIPTION
**Pull request by mpeyper**
This one is huge.  I don't think a single line of the version 1 survived.  It will probably be easier to just look at or clone [my fork](https://github.com/mpeyper/redux-subspace) than to read this PR, but review however you feel is easiest for you.

The changes here are plentiful:

- Complete refactor of core subspace code
  - Middleware support
    - Improved support for Redux middleware
    - Added middleware pipelines for subspaces as well
  - More versatile ways to create subspaces (less duplication in keys for common cases)
- Library has been split into multiple packages
  - redux-subspace: The core of the library
  - react-redux-subspace: React bindings to create subspaces for components
  - redux-subspace-saga: Support for creating subspaced sagas compatible with redux-saga
  - redux-subspace-wormhole: A redux-subspace middleware that replaces the `root` node functionality
- Improved documentation

### CODE REVIEW

**Comment by mpeyper** [comment]
I haven't done much (read: any) spell/grammar checking on the new docs, but I really wanted to get this up for review.  If you see any, comment them an I'll fix them up in due course.

**Comment by mpeyper** [comment]
Also, this should resolve #18, #19, #31.

**Comment by mpeyper** [comment]
You can [see the build here](https://travis-ci.org/mpeyper/redux-subspace) with all the tests that run for each package.

**Comment by vivian-farrell** [comment]
Really great effort Michael. I will start digging through.

**Comment by mpeyper** [comment]
Just added a small change to the saga middleware.  Now, when using the replacement `createSagaMiddleware` you don't need to wrap the root saga in `provideStore` (it handles this automatically now).

**Comment by vivian-farrell** [comment]
Is the import in https://github.com/mpeyper/redux-subspace/blob/master/packages/react-redux-subspace/src/components/SubspaceProvider.js for subspace correct? Redux-subspace is not in the list of packages in the package.json so how is it resolved?

**Comment by vivian-farrell** [comment]
My bad, it is in the list. Ignore the comment above.

**Comment by jpeyper** [comment]
The code looks good and test coverage is awesome. Good job.

Docs also seem good, although I think there may be some tweaking over time.

I think we should merge this as is and then fix any docs problems on master.

**Pull request merged**
