### PR TITLE
Fix typo in subspaced.md

### PR DESCRIPTION
**Pull request by James-E-Adams**

### CODE REVIEW

**Comment by jpeyper** [comment]
Haha, thanks. We need a good proof reader.

**Comment by James-E-Adams** [comment]
Haha it felt a little silly opening the PR for a single char, but if I find anymore whilst reading the documentation, I'll try bunch them together.  :)

**Comment by mpeyper** [comment]
Also, feel free to leave any feedback of the docs in #52.  I've been a bit slack it following through on that one, but any thoughts you might have on it are more than welcome.

**Comment by James-E-Adams** [comment]
OK, will do if I get a chance. :)

**Pull request merged**
