### PR TITLE
Remove recompose dependency

### PR DESCRIPTION
**Pull request by Byron-Wall**
| Q                       | A 
| ----------------------- | ---
| Fixed Issues?           | Fixes https://github.com/ioof-holdings/redux-subspace/issues/508
| Patch: Bug Fix?         | 👍
| Tests Added + Pass?     | Yes

Adds createDisplayName util to react-redux-subspace, replaces recompose/wrapDisplayName in react-redux-subspace/src/components/parentSpaced.js and react-redux-subspace/src/components/subspaced.js, and adds test file for createDisplayName util.  This removes the `recompose` dependency, which is currently unmaintained and returning a denial-of-service security issue from `npm audit`

### CODE REVIEW

**Comment by mpeyper** [comment]
Hi @Byron-Wall,

Sorry it's taken a while to get to this review.

The changes itself is fine and I'm happy to accept it, but there is a lot of formatting changes that seem unnecessary for replacing a function (I understand that there are no formatting rules in place to help with that).

I'll merge as-is, but please don't be offended if I add a prettier config and it all gets formatted back again.

**Comment by Byron-Wall** [comment]
Hey, thanks for the review, Ive been out all week, so the timing has worked out well for me.  I am in no way offended if a prettier config changes formatting.  Thanks!

**Comment by Byron-Wall** [comment]
Hey @mpeyper , would it be possible to let me know when you are able to publish this update to NPM?

**Comment by mpeyper** [comment]
@Byron-Wall Yes, sorry. Plan was to do it yesterday, but had some production issues at work and swamped me.

I'll endeavour to do it today.

**Comment by mpeyper** [comment]
@Byron-Wall this has been release in `v6.2.0` now.

**Comment by Byron-Wall** [comment]
@mpeyper thanks for releasing/letting me know!

**Pull request merged**
